language: node_js

node_js:
  - node # will use latest node

before_script: # commands to run before the build step
   - travis_retry npm install -dd -g firebase-tools # installs firebase to run firebase deploy

script: # the build step
  - npm install
  - npm run critical
  - npm run minify
after_success:
  - npm run travis-deploy-test
  - test $TRAVIS_BRANCH = "master" && npm run travis-deploy
notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change
